### ISSUE TITLE
Add support for streaming data.

### ISSUE THREAD

**Issue by srijs** [srijs/rusha#2]
Add support to calculate hashes on the fly for chunks of data.

The goal is to be compatible to Node.JS' `crypto.createHash`. (http://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm)

Steps to be done:

✓ Transfer all RushaCore context to the heap
✓ Isolate function to pad data
-- Add `fill` state that indicates fullness of buffer and acts as write-offset for `conv`
-- Add `update` and `finalize` methods
-- Factor both methods into an object returned by the `createHash` method

**Comment by ldwedari** [comment]
I've added some simple methods to Rusha to support streaming/chunking. I'm not following the goals of this task, but maybe it is still helpful. The code is in the branch: 

https://github.com/ldwedari/rusha/tree/Chunking

**Comment by srijs** [comment]
Hi @ldwedari, I appreciate you tackling this problem. I cleaned up your changes a bit and pushed them to the [feature/chunking](https://github.com/srijs/rusha/tree/feature/chunking) branch. I also added a test case, which is unfortunately failing. If you want to continue pursuing this, I suggest you try to make the test case work.

**Comment by Strayer** [comment]
Hi @srijs,

I want to use Rusha in a project where large files up to several gigabytes need to be hashed. I already checked out other solutions (Forge, crypto-browserify, crypto-js) but they are either absolutely huge, don't work in my browserify workflow, or sadly rather slow. Putting those files into memory to hash them with Rusha will obviously not work, so I decided to help getting this feature done :)

Since I'm not very experienced with crypto tech I first added the basic digest tests for chunking. It seems like only updating the hash with String objects is failing, as using buffers or arrays seems to work. I guess something happens on the way of converting the Strings to binary data? Not entirely sure about this one...

I added the tests in my chunking branch here: https://github.com/Strayer/rusha/commit/930bf82159198225a29f8aeafdde57f06f22dcc7

**Comment by Strayer** [comment]
The tests can be found in my chunking branch, commits are https://github.com/Strayer/rusha/commit/e58c218 and https://github.com/Strayer/rusha/commit/11570db

I also discovered that hashing an empty string with update() doesn't work correctly. Just using update() once does indeed work, so I guess the actual problem appears as soon as update() is called a second time, but I couldn't wrap my head around this right now.

**Comment by srijs** [comment]
Thinking a bit about how to work towards a working implementation for streaming data, one of the checkpoints along the way would be to support `update`, but with the restriction that all inputs except the last one (which would be passed to finalize) have to be a multiple of the SHA1 block size (512 bit). That way, we don't have to care about retaining bits of data between updates, since all input can be processed completely.

**Comment by srijs** [comment]
Streaming data has been implemented. Closing.
